import {
    Tag,
    BookOpen,
    Code,
    Palette,
    Music,
    Camera,
    Video,
    FileText,
    Globe,
    ShoppingBag,
    Heart,
    Zap,
    Lightbulb,
    Coffee,
    Gift,
    Award,
    Trophy,
    Target,
    Users,
    Settings,
    Home,
    Building,
    Briefcase,
    GraduationCap,
    Book,
    PenTool,
    Mic,
    Headphones,
    Film,
    Image,
    File,
    Folder,
    Database,
    Server,
    Cloud,
    Wifi,
    Smartphone,
    Laptop,
    Monitor,
    Printer,
    Keyboard,
    Mouse,
    HardDrive,
    Cpu,
    Activity,
    BarChart,
    LineChart,
    PieChart,
    TrendingUp,
    TrendingDown,
    DollarSign,
    Euro,
    CreditCard,
    Wallet,
    Banknote,
    Coins,
    PiggyBank,
    ShoppingCart,
    Package,
    Truck,
    Car,
    Bike,
    Plane,
    Train,
    Ship,
    Bus,
    Compass,
    Map,
    Navigation,
    Flag,
    MapPin,
    type LucideIcon,
} from "lucide-react"

/**
 * Mapping nom d'icône (stocké en base par le superadmin) → composant lucide.
 * Les clés DOIVENT correspondre exactement à celles du sélecteur d'icône côté
 * SaaS (superadmin marketplace > catégories) pour que chaque catégorie affiche
 * l'icône réellement configurée.
 */
const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
    tag: Tag,
    bookOpen: BookOpen,
    code: Code,
    palette: Palette,
    music: Music,
    camera: Camera,
    video: Video,
    fileText: FileText,
    globe: Globe,
    shoppingBag: ShoppingBag,
    heart: Heart,
    zap: Zap,
    lightbulb: Lightbulb,
    coffee: Coffee,
    gift: Gift,
    award: Award,
    trophy: Trophy,
    target: Target,
    users: Users,
    settings: Settings,
    home: Home,
    building: Building,
    briefcase: Briefcase,
    graduationCap: GraduationCap,
    book: Book,
    penTool: PenTool,
    mic: Mic,
    headphones: Headphones,
    film: Film,
    image: Image,
    file: File,
    folder: Folder,
    database: Database,
    server: Server,
    cloud: Cloud,
    wifi: Wifi,
    smartphone: Smartphone,
    laptop: Laptop,
    monitor: Monitor,
    printer: Printer,
    keyboard: Keyboard,
    mouse: Mouse,
    hardDrive: HardDrive,
    cpu: Cpu,
    activity: Activity,
    barChart: BarChart,
    lineChart: LineChart,
    pieChart: PieChart,
    trendingUp: TrendingUp,
    trendingDown: TrendingDown,
    dollarSign: DollarSign,
    euro: Euro,
    creditCard: CreditCard,
    wallet: Wallet,
    banknote: Banknote,
    coins: Coins,
    piggyBank: PiggyBank,
    shoppingCart: ShoppingCart,
    package: Package,
    truck: Truck,
    car: Car,
    bike: Bike,
    plane: Plane,
    train: Train,
    ship: Ship,
    bus: Bus,
    compass: Compass,
    map: Map,
    navigation: Navigation,
    flag: Flag,
    mapPin: MapPin,
}

/**
 * Résout l'icône d'une catégorie depuis son nom stocké. Repli sur `Tag`
 * (même défaut que le formulaire superadmin) quand l'icône est absente/inconnue.
 */
export function getCategoryIcon(icon: string | null | undefined): LucideIcon {
    if (icon && CATEGORY_ICON_MAP[icon]) return CATEGORY_ICON_MAP[icon]
    return Tag
}
